### ISSUE TITLE
The Game starts  freeze every 2-3 seconds after turning on gold mode.

### ISSUE THREAD

**Issue by karnauhmax** [DeNcHiK3713/MixMod#1]
The pc specs are: 1060 6gb + i5 4440 + 16 gb ram. When I turn on gold mode game starts to freeze every 2-3 seconds on 0.5 seconds

**Comment by DeNcHiK3713** [comment]
It also freezes when the option is disabled (and the whole mod too) but with a full golden deck (golden Whizbang the Wonderful) on my rtx 2060 super + ryzen 5 3600x + 16gb ram. I think the problem is in the game and not in the mod.
