### ISSUE TITLE
29.2 Patch

### ISSUE THREAD

**Issue by bsun0000** [DeNcHiK3713/MixMod#3]
Близы что-то накрутили в коде, теперь плагин работает некорректно. К примеру скорость анимаций больше не меняется хоткеями, закрытие игры - вылетает с запуском WerFault.exe, дальше этого не тестировал.

**Comment by DeNcHiK3713** [comment]
Fixed in https://github.com/DeNcHiK3713/MixMod/releases/tag/v1.0.37
